config/routes.rb
Rails.application.routes.draw do
  resources :marksheets
  root "marksheets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marksheet.rb
class Marksheet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/marksheets_controller.rb
class MarksheetsController < ApplicationController
  before_action :set_marksheet, only: %i[ show edit update destroy ]

  # GET /marksheets or /marksheets.json
  def index
    @marksheets = Marksheet.all
  end

  # GET /marksheets/1 or /marksheets/1.json
  def show
  end

  # GET /marksheets/new
  def new
    @marksheet = Marksheet.new
  end

  # GET /marksheets/1/edit
  def edit
  end

  # POST /marksheets or /marksheets.json
  def create
    @marksheet = Marksheet.new(marksheet_params)

    respond_to do |format|
      if @marksheet.save
        format.html { redirect_to @marksheet, notice: "Marksheet was successfully created." }
        format.json { render :show, status: :created, location: @marksheet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @marksheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marksheets/1 or /marksheets/1.json
  def update
    respond_to do |format|
      if @marksheet.update(marksheet_params)
        format.html { redirect_to @marksheet, notice: "Marksheet was successfully updated." }
        format.json { render :show, status: :ok, location: @marksheet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @marksheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marksheets/1 or /marksheets/1.json
  def destroy
    @marksheet.destroy
    respond_to do |format|
      format.html { redirect_to marksheets_url, notice: "Marksheet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marksheet
      @marksheet = Marksheet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marksheet_params
      params.require(:marksheet).permit(:name, :subject_one, :subject_two, :subject_three, :subject_four, :subject_five)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marksheets_helper.rb
module MarksheetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentMarksheet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/marksheets/_form.html.erb
<%= form_with(model: marksheet, local: true) do |form| %>
  <% if marksheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marksheet.errors.count, "error") %> prohibited this marksheet from being saved:</h2>

      <ul>
      <% marksheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :subject_one %>
    <%= form.text_field :subject_one %>
  </div>

  <div class="field">
    <%= form.label :subject_two %>
    <%= form.text_field :subject_two %>
  </div>

  <div class="field">
    <%= form.label :subject_three %>
    <%= form.text_field :subject_three %>
  </div>

  <div class="field">
    <%= form.label :subject_four %>
    <%= form.text_field :subject_four %>
  </div>

  <div class="field">
    <%= form.label :subject_five %>
    <%= form.text_field :subject_five %>
  </div>

  <div class="actions"  class="button-33" >
    <%=  form.submit %>
  </div>
<% end %>

app/views/marksheets/edit.html.erb
<div class="header-section">
<h1>Editing Marksheet</h1>
</div>
<%= render 'form', marksheet: @marksheet %>

<%= link_to 'Show', @marksheet %> |
<%= link_to 'Back', marksheets_path %>

app/views/marksheets/index.html.erb
<p id="notice"><%= notice %></p>
<div class="header-section">
<h1>Student Marksheets</h1>
</div>
<table class="table-sectioin">
  <thead class="thread-section" id="update_thread-section">
    <tr class="tr-section" >
      <th>Name</th>
      <th>Subject one</th>
      <th>Subject two</th>
      <th>Subject three</th>
      <th>Subject four</th>
      <th>Subject five</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="thread-section">
    <% @marksheets.each do |marksheet| %>
      <tr class="tr-section">
        <td><%= marksheet.name %></td>
        <td><%= marksheet.subject_one %></td>
        <td><%= marksheet.subject_two %></td>
        <td><%= marksheet.subject_three %></td>
        <td><%= marksheet.subject_four %></td>
        <td><%= marksheet.subject_five %></td>
        <td><%= link_to 'Show', marksheet %></td>
        <td><%= link_to 'Edit', edit_marksheet_path(marksheet) %></td>
        <td><%= link_to 'Destroy', marksheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marksheet', new_marksheet_path %>

app/views/marksheets/new.html.erb
<div class="header-section">

<h1>New Marksheet</h1>
</div>
<%= render 'form', marksheet: @marksheet %>

<%= link_to 'Back', marksheets_path %>

app/views/marksheets/show.html.erb
<p id="notice"><%= notice %></p>
<div>
<p class="details-section">
<strong>Name:</strong>
<%= @marksheet.name %>
</p>

<p class="details-section">
<strong>Subject one:</strong>
<%= @marksheet.subject_one %>
</p>

<p class="details-section">
<strong>Subject two:</strong>
<%= @marksheet.subject_two %>
</p>

<p class="details-section">
<strong>Subject three:</strong>
<%= @marksheet.subject_three %>
</p>

<p class="details-section">
<strong>Subject four:</strong>
<%= @marksheet.subject_four %>
</p>

<p class="details-section">
<strong>Subject five:</strong>
<%= @marksheet.subject_five %>
</p>

<%= link_to 'Edit', edit_marksheet_path(@marksheet) %> |
<%= link_to 'Back', marksheets_path %>
</div>